/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Bicho(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/bichox.glb");
  const { actions } = useAnimations(animations, group);

  React.useEffect(() =>
  {
    console.log(actions)
    actions.ArmatureAction.play()
    actions.ArmatureAction.timeScale = 0.1
  },[])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[0, 0.463, -0.376]} scale={5}>
          <group name="Sphere">
            <skinnedMesh
              name="Sphere_1"
              geometry={nodes.Sphere_1.geometry}
              material={materials.Material_0}
              skeleton={nodes.Sphere_1.skeleton}
            />
            <skinnedMesh
              name="Sphere_2"
              geometry={nodes.Sphere_2.geometry}
              material={materials["Material.002"]}
              skeleton={nodes.Sphere_2.skeleton}
            />
          </group>
          <primitive object={nodes.Bone} />
          <primitive object={nodes.izqik} />
          <primitive object={nodes.Bone006} />
          <primitive object={nodes.derchaik} />
          <primitive object={nodes.Bone010} />
          <primitive object={nodes.ikcabeza} />
          <primitive object={nodes.Bone015} />
          <primitive object={nodes.colaik} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/bichox.glb");
